#!/bin/bash

cat <<\EOF > /etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

exit 0
EOF

####################################################
#  !!! DO NOT CHANGE ANYTHING ABOVE THIS LINE !!!  #
####################################################

# Wait limit for connection and retry counts
WAIT_LIMIT=30
CONNECTION_RETRY=0

# Check for internet connection. Don't even bother running if not connected.
until ping -c 1 www.google.com > /dev/null ; do
    sleep 1
    retry=$(($CONNECTION_RETRY+1))
    if [ $CONNECTION_RETRY -eq $WAIT_LIMIT ]; then
        echo "[ERR] HQ | Interface not connected and limit reached... | $(date)" >> /var/log/hq-install.log
        exit 0
    fi
done

echo "HQapp - Initializing the Home Assistant installation " >> /var/log/hq-install.log
sudo apt-get update
sudo apt-get upgrade -y

echo "HQapp - Installing Python 3.6 " >> /var/log/hq-install.log
sudo apt-get -y install build-essential checkinstall
sudo apt-get -y install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev python-dev

sudo wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz -P /usr/src
sudo mkdir /usr/src/Python-3.6.0
chmod 755 /usr/src/Python-3.6.0
sudo tar xzf /usr/src/Python-3.6.0.tgz -C /usr/src/

sudo sh -c 'cd /usr/src/Python-3.6.0 && ./configure' >> /var/log/python-install
sudo sh -c 'cd /usr/src/Python-3.6.0 && make install' >> /var/log/python-install

sudo python3.6 -V >> /var/log/hq-install.log

sudo useradd -rm homeassistant -G dialout,gpio
sudo python3.6 -m pip install aiohttp_cors
# python3 -m pip install --index-url https://test.pypi.org/simple hq-app
sudo python3.6 -m pip install homeassistant
echo "HQapp - installation of Home Assistant installation complete" >> /var/log/hq-install.log

echo "Setting up the auto-start configuration for Home Assistant" >> /var/log/hq-install.log

cat <<\EOF > /etc/systemd/system/home-assistant@homeassistant.service

[Unit]
Description=Home Assistant
After=network-online.target

[Service]
Type=simple
User=%i
ExecStart=/usr/local/bin/hass

[Install]
WantedBy=multi-user.target

EOF

echo "Loading new configuration known to daemon" >> /var/log/hq-install.log
sudo systemctl --system daemon-reload

echo "Enabling the home-assistant service" >> /var/log/hq-install.log
sudo systemctl enable home-assistant@homeassistant

echo "Starting home-assistant..." >> /var/log/hq-install.log
sudo systemctl start home-assistant@homeassistant

echo "Starting HQ Home UI installation..." >> /var/log/hq-install.log
sudo bash /home/hq-ui-init
####################################################
#  !!! DO NOT CHANGE ANYTHING BELOW THIS LINE !!!  #
####################################################

rm /boot/rpi_init

source /etc/rc.local
exit 0


